### ISSUE TITLE
Find a name

### ISSUE THREAD

**Issue by grandsmarquis** [verynifty/fastdapp#4]
Here are the current submissions gathered by [GreatDragonian](https://forum.musedao.io/u/GreatDragonian) :

MUSURE PRO
MuseSwift
TurboForge
Ethlets Masonry
Wizeth
Magiceth
Front3nd
Forg3
Wysiwygeth
aMUSEment Park
DappIt
What You Sew is What You geth
aMUSE
Elixir
BUIDL
eZBuidl
Contract Canvas
Block Fabric
Dapp Dexterity
Dapplicious
Dappster
Dappmonster
Dappground
DappFactory
ScriptLab
Codex
ToolBox
Cook
START
dApptory
Turbodapps

**Comment by khelil** [comment]
NoNo
SmartBlock
BuBlock
Blockator
BlockTag
MetaBlock
MadBlock
MekaBlock
Musidity
zApp
xApp
Xetris

😬

**Comment by eastrgn** [comment]
Lumos

**Comment by grandsmarquis** [comment]
A vote is here just to check
https://forum.musedao.io/t/muse-build-presentation-name-contest/80/39?u=jules
